export const ROUTES = {
  home: "/",
  cart: "/cart",
  login: "/login",
  users: "/users",
  orders: "/orders",
  profile: "/profile",
  register: "/register",
  checkout: "/checkout",
  wishlist: "/wishlist",
  products: "/products",
  dashboard: "/dashboard",
  productNew: "/products/new",
  forgotPassword: "/forgot-password",
  user: (id: string) => `/users/${id}`,
  order: (id: string) => `/orders/${id}`,
  product: (slug: string) => `/products/${slug}`,
} as const;
