export const ROUTES = {
  home: "/",
  cart: "/cart",
  admin: "/admin",
  login: "/login",
  orders: "/orders",
  profile: "/profile",
  register: "/register",
  checkout: "/checkout",
  wishlist: "/wishlist",
  products: "/products",
  dashboard: "/dashboard",
  adminUsers: "/admin/users",
  adminOrders: "/admin/orders",
  adminProducts: "/admin/products",
  forgotPassword: "/forgot-password",
  order: (id: string) => `/orders/${id}`,
  adminProductNew: "/admin/products/new",
  product: (slug: string) => `/products/${slug}`,
  adminUser: (id: string) => `/admin/users/${id}`,
  adminOrder: (id: string) => `/admin/orders/${id}`,
} as const;
